/**
 * @module routes
 */

export const routes = {
    protected: {
        properties: '/property',
        add_property: '/property/add',
        add_property_ai: '/property/create',
        add_category_listing: '/category-listing/create',
        publish: '/publish',
        publish_category_choice: '/publish/category',
        reels: '/reels',
        reels_mine: '/reels/mine',
        reels_add: '/reels/add',
        reels_select_property: '/reels/select-property',
        add_home: '/property/add/home',
        add_apartment: '/property/add/apartment',
        add_building: '/property/add/building',
        add_desk: '/property/add/desk',
        add_studio: '/property/add/studio',
        add_villa: '/property/add/villa',
        add_room: '/property/add/room',
        add_kiosk: '/property/add/kiosk',
        add_shop: '/property/add/shop',
        add_land: '/property/add/land',
        add_duplex: '/property/add/duplex',
        add_warehouse: '/property/add/warehouse',
        account: '/profil',
        favoris: '/favoris',
        profil: '/profil',
        profil_informations: '/profil/informations',
        become_announcer: '/profil/devenir-annonceur',
        login_and_security: '/login-and-security',
        notifications: '/settings',
        notification_list: '/list-notifications',
        my_balance: '/my-balance/history',
        my_balance_history: '/my-balance/history',
        my_balance_recharge: '/my-balance/recharge',
        verify_phone: '/verify-phone',
        advertising: '/advertising',
        advertising_create: '/advertising/create',
        gifts: '/gifts',
    },
    public: {
        signin: '/signin',
        signup: '/signup',
        completeProfile: '/complete-profile',
        homePage: '/',
        reset_password: '/password-reset',
        passwordResetRequest: '/request-password-reset',
        passwordResetFailure: '/password-reset-failure',
        emailAlreadyVerified: '/email-already-verified',
        emailVerificationSuccess: '/email-verification-success',
        confidentiality: '/privacy-policy',
        terms_of_use: '/terms-of-use',
        announcer_terms: '/announcer-terms',
        data_deletion: '/data-deletion',
        search: '/search',
        search_property: '/search',
        search_with_ia: '/search-with-ia',
        immobilier: '/immobilier',
        // Nouvelles routes blog et guide
        blog: '/blog',
        blog_tendances_marche: '/blog/tendances-marche-immobilier-gabon-2024',
        blog_financement: '/blog/financement-immobilier-gabon',
        blog_commissions_demarcheurs: '/blog/commissions-demarcheurs-logements-gabon',
        blog_structurer_annonces: '/blog/structurer-annonces-engagement',
        blog_proptech: '/blog/proptech-innovation-immobilier-gabon',
        // Nouvelles routes blog ajoutées
        blog_guide_quartiers_libreville: '/blog/guide-quartiers-libreville-2024-2025',
        blog_guide_quartiers_port_gentil: '/blog/guide-quartiers-port-gentil-2024-2025',
        blog_rentabilite_immobiliere: '/blog/rentabilite-immobiliere-gabon-2024-2025',
        blog_actualites_immobilieres: '/blog/actualites-immobilieres-gabon-2024-2025',
        blog_conseils_negociation: '/blog/conseils-negociation-immobiliere-gabon',
        blog_demarches_administratives: '/blog/demarches-administratives-immobilier-gabon-2024',
        guide_immobilier_gabon: '/guide-immobilier-gabon',
        advertise: '/faire-de-la-pub',
        property: '/property',
        search_requests: '/demandes-recherche',
        search_requests_publish: '/demandes-recherche/publier',
    },
    public_google: {
        homePage: '/',
        immobilier: '/immobilier',
        search: '/search',
        search_with_ia: '/search-with-ia',
        confidentiality: '/privacy-policy',
        terms_of_use: '/terms-of-use',
        announcer_terms: '/announcer-terms',
        // Routes importantes pour Google
        blog: '/blog',
        blog_tendances_marche: '/blog/tendances-marche-immobilier-gabon-2024',
        blog_financement: '/blog/financement-immobilier-gabon',
        blog_commissions_demarcheurs: '/blog/commissions-demarcheurs-logements-gabon',
        blog_structurer_annonces: '/blog/structurer-annonces-engagement',
        blog_proptech: '/blog/proptech-innovation-immobilier-gabon',
        // Nouvelles routes blog ajoutées
        blog_guide_quartiers_libreville: '/blog/guide-quartiers-libreville-2024-2025',
        blog_guide_quartiers_port_gentil: '/blog/guide-quartiers-port-gentil-2024-2025',
        blog_rentabilite_immobiliere: '/blog/rentabilite-immobiliere-gabon-2024-2025',
        blog_actualites_immobilieres: '/blog/actualites-immobilieres-gabon-2024-2025',
        blog_conseils_negociation: '/blog/conseils-negociation-immobiliere-gabon',
        blog_demarches_administratives: '/blog/demarches-administratives-immobilier-gabon-2024',
        guide_immobilier_gabon: '/guide-immobilier-gabon',
        property: '/property',
        search_requests: '/demandes-recherche',
    }
}
