export const DEFAULT_TAG_NAMES = [
  "Travail",
  "Famille",
  "Couple",
  "Villa",
  "Sous barrière",
  "Meublé",
  "Centre-ville",
  "Vacances",
  "Nature",
  "Montagne",
  "Piscine",
  "Animaux admis",
  "Commerces proches",
  "Transport proche",
  "Parking",
  "Wi-Fi",
  "Sécurisé",
  "Vélo",
  "Activités sportives",
  "Adapté aux enfants",
  "Accessible handicapés",
  "Étudiant",
  "Calme et tranquillité",
  "Proche de la plage",
  "Duplex",
  "Boutique",
  "Balcon",
  "Terrasse",
  "Collocation",
  "Garage",
  "Court séjour",
  "Propriétaire",
  "Agence",
] as const;
