import type { AdminPermission, AdminRole } from "@/modules/iam/domain/types";

const ROLE_PERMISSIONS: Record<AdminRole, AdminPermission[]> = {
  super_admin: ["*.*"],
  operations_admin: [
    "admins.read",
    "admins.view_presence",
    "admins.view_last_login",
    "users.read",
    "users.search",
    "users.create",
    "users.update",
    "users.suspend",
    "users.reactivate",
    "users.view_presence",
    "users.view_last_seen",
    "announcers.create",
    "announcers.update",
    "listings.read",
    "listings.search",
    "listings.export",
    "listings.create",
    "listings.update",
    "listings.state.update",
    "listings.status.update",
    "listings.archive",
    "listings.unarchive",
    "listings.bulk.update",
    "listings.bulk.archive",
    "listings.bulk.unarchive",
    "listings.duplicates.read",
    "listings.duplicates.resolve",
    "listings.duplicates.recompute",
    "listings.approve",
    "listings.reject",
    "transactions.read",
    "credits.pack_manage",
    "analytics.search_read",
    "analytics.traffic_read",
    "ads_analytics.read",
    "ads_analytics.export",
    "ads_analytics.alerts.read",
    "ads_analytics.alerts.manage",
    "ads_campaigns.read",
    "ads_campaigns.create",
    "ads_campaigns.update",
    "ads_campaigns.publish",
    "ads_campaigns.payment",
    "advertisers.manage",
    "ads_pricing.manage",
    "social_import.read",
    "social_import.export",
    "social_import.source.read",
    "social_import.source.create",
    "social_import.source.update",
    "social_import.source.pause",
    "social_import.source.revoke",
    "social_import.consent.manage",
    "social_import.run",
    "social_import.run.dry",
    "social_import.run.prod",
    "social_import.job.read",
    "social_import.job.retry",
    "social_import.review",
    "social_import.publish",
    "social_import.reject",
    "social_import.decision.read",
    "social_import.settings.read",
    "social_import.settings.update",
    "social_import.scheduler.manage",
    "audit_logs.read",
  ],
  moderation_admin: [
    "users.read",
    "users.search",
    "users.view_presence",
    "users.view_last_seen",
    "announcers.read",
    "listings.read",
    "listings.search",
    "listings.export",
    "listings.state.update",
    "listings.status.update",
    "listings.archive",
    "listings.unarchive",
    "listings.bulk.archive",
    "listings.bulk.unarchive",
    "listings.duplicates.read",
    "listings.duplicates.resolve",
    "listings.approve",
    "listings.reject",
    "social_import.read",
    "social_import.export",
    "social_import.source.read",
    "social_import.source.pause",
    "social_import.run",
    "social_import.run.dry",
    "social_import.job.read",
    "social_import.job.retry",
    "social_import.review",
    "social_import.publish",
    "social_import.reject",
    "social_import.decision.read",
    "social_import.settings.read",
    "audit_logs.read",
  ],
  finance_admin: [
    "users.read",
    "users.search",
    "users.view_presence",
    "users.view_last_seen",
    "credits.read",
    "credits.grant",
    "credits.pack_manage",
    "transactions.read",
    "refunds.read",
    "refunds.approve",
    "audit_logs.read",
    "analytics.traffic_read",
    "ads_analytics.read",
    "ads_analytics.export",
    "ads_analytics.alerts.read",
  ],
  support_admin: [
    "users.read",
    "users.search",
    "users.create",
    "users.suspend",
    "users.reactivate",
    "users.view_presence",
    "users.view_last_seen",
    "announcers.read",
    "announcers.create",
    "announcers.update",
    "transactions.read",
    "listings.create",
    "listings.search",
    "listings.update",
    "listings.state.update",
    "listings.archive",
    "listings.unarchive",
    "listings.duplicates.read",
    "listings.duplicates.resolve",
    "social_import.read",
    "social_import.source.read",
    "social_import.source.create",
    "social_import.source.update",
    "social_import.source.pause",
    "social_import.run",
    "social_import.run.dry",
    "social_import.job.read",
    "social_import.review",
    "social_import.reject",
    "social_import.decision.read",
    "social_import.settings.read",
    "audit_logs.read",
    "analytics.search_read",
    "analytics.traffic_read",
  ],
  analyst_admin: [
    "admins.read",
    "admins.view_presence",
    "admins.view_last_login",
    "users.read",
    "users.search",
    "users.view_presence",
    "users.view_last_seen",
    "listings.read",
    "listings.search",
    "listings.export",
    "listings.duplicates.read",
    "transactions.read",
    "audit_logs.read",
    "analytics.search_read",
    "analytics.traffic_read",
    "ads_analytics.read",
    "ads_analytics.export",
    "ads_analytics.alerts.read",
    "social_import.read",
    "social_import.export",
    "social_import.source.read",
    "social_import.job.read",
    "social_import.review",
    "social_import.decision.read",
    "social_import.settings.read",
  ],
};

export function resolvePermissions(roles: AdminRole[]) {
  if (roles.includes("super_admin")) {
    return ["*.*"] as AdminPermission[];
  }

  const all = roles.flatMap((role) => ROLE_PERMISSIONS[role] ?? []);
  return Array.from(new Set(all));
}

export function hasPermission(
  permissions: AdminPermission[],
  required: AdminPermission,
) {
  return permissions.includes("*.*") || permissions.includes(required);
}
