export const trackingEvents = {
  PAGE_VIEW: 'page_view',
  PAGE_HOME_VIEW: 'page_home_view',
  PAGE_SEARCH_VIEW: 'page_search_view',
  PAGE_SEARCH_WITH_IA_VIEW: 'page_search_with_ia_view',
  PAGE_PROPERTY_DETAILS_VIEW: 'page_property_details_view',
  PAGE_SIGNIN_VIEW: 'page_signin_view',
  PAGE_SIGNUP_VIEW: 'page_signup_view',
  CTA_AUTH_SIGNIN_CLICK: 'cta_auth_signin_click',
  CTA_AUTH_SIGNUP_CLICK: 'cta_auth_signup_click',
  CTA_AUTH_GOOGLE_CLICK: 'cta_auth_google_click',
  CTA_HOME_PUBLISH_CLICK: 'cta_home_publish_click',
  CTA_HOME_SEARCH_CLICK: 'cta_home_search_click',
  CTA_HOME_EXPLORE_CLICK: 'cta_home_explore_click',
  CTA_SEARCH_SUBMIT_CLICK: 'cta_search_submit_click',
  CTA_SEARCH_WITH_IA_ENTRY_CLICK: 'cta_search_with_ia_entry_click',
  CTA_PROPERTY_CARD_CLICK: 'cta_property_card_click',
  CTA_PROPERTY_WHATSAPP_CONTACT_CLICK: 'cta_property_whatsapp_contact_click',
  CTA_PROPERTY_FAVORITE_ADD_CLICK: 'cta_property_favorite_add_click',
  CTA_PROPERTY_FAVORITE_REMOVE_CLICK: 'cta_property_favorite_remove_click',
  CTA_BALANCE_RECHARGE_WHATSAPP_CLICK: 'cta_balance_recharge_whatsapp_click',
  AI_SEARCH_MESSAGE_SENT: 'ai_search_message_sent',
  AI_SEARCH_SEARCH_CALL: 'ai_search_search_call',
  AI_SEARCH_RESULT_CLICK: 'ai_search_result_click',
  AI_SEARCH_CREDIT_DEBITED: 'ai_search_credit_debited',
  BUSINESS_AUTH_SIGNIN_SUCCESS: 'business_auth_signin_success',
  BUSINESS_AUTH_SIGNUP_SUCCESS: 'business_auth_signup_success',
  CTA_PUBLISH_AUTH_MODAL_OPEN: 'cta_publish_auth_modal_open',
  CTA_PUBLISH_AUTH_CHOICE_SIGNUP: 'cta_publish_auth_choice_signup',
  CTA_PUBLISH_AUTH_CHOICE_SIGNIN: 'cta_publish_auth_choice_signin',
  BUSINESS_PUBLISH_AUTH_SIGNUP_SUCCESS: 'business_publish_auth_signup_success',
  BUSINESS_PUBLISH_AUTH_SIGNIN_SUCCESS: 'business_publish_auth_signin_success',
  BUSINESS_PUBLISH_AUTH_BECOME_ANNOUNCER_SUCCESS: 'business_publish_auth_become_announcer_success',
  BUSINESS_PROPERTY_AUTO_PUBLISH_SUCCESS: 'business_property_auto_publish_success',
  BUSINESS_PROPERTY_AUTO_PUBLISH_FAILED: 'business_property_auto_publish_failed',
} as const;

export type TrackingEventName = (typeof trackingEvents)[keyof typeof trackingEvents];

export type TrackingRoleContext = 'visitor' | 'user' | 'announcer';
